# Generated by Django 3.2.21 on 2023-09-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_roomamenities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomAmenities',
            new_name='RoomAmenity',
        ),
    ]
