# Generated by Django 3.2.21 on 2023-09-25 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_roomamenities_roomamenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.AddField(
            model_name='amenity',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='equipments',
            field=models.ManyToManyField(related_name='room_equipments', to='core.Amenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='RoomAmenity',
        ),
        migrations.AddField(
            model_name='amenity',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipment'),
        ),
    ]
